#!/usr/bin/env python

import sys
import socket, struct

addr = ('localhost', 10086)
header = '''GET / HTTP/1.1\r\nHost: app26745-4.qzoneapp.com:8000\r\n\r\n'''

def travel(data):
    global addr, header
    packer = struct.Struct('I')
    sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    sock.connect(addr)
    sock.send(struct.pack('%ds' % len(header), header) + packer.pack(data))
    reply = sock.recv(4)
    return packer.unpack(reply)[0]

if __name__ == '__main__':
    addr = (sys.argv[1], int(sys.argv[2])) if len(sys.argv) == 3 else ('localhost', 10086)
    data = 26745    # `travel()` require an int32_t
    print "sent: %d, received: %d" %(data, travel(data)),

